In [20]:
from sklearn.feature_extraction.text import CountVectorizer
import glob
import pandas as pd
import nltk
import numpy as np
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk import pos_tag

In [21]:
# modeli za ustrezno obdelavo stavkov, besed, ločil....
nltk.download('punkt')     # stavki, besede
nltk.download('wordnet') #lemmatizacija
nltk.download('averaged_perceptron_tagger') #POS tagganje
nltk.download('omw-1.4') 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [22]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [23]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [24]:
# tokenization and lemmatization 
lemmatizer= WordNetLemmatizer()

In [25]:
# pokupčkamo besede s podobnim korenom, pomenom skupaj
# run, runs, running -> run
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('RB'):
        return wordnet.ADV
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    else:
        return wordnet.NOUN

In [26]:
def tokenize_lematize(tekst):
    tokens = word_tokenize(tekst.lower())  # vse besede pišemo z malo začetnico
    tagged = pos_tag(tokens)
    return [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged
        if word.isalpha()    # znebimo se ločil, st,...
    ]

In [27]:
from sklearn.feature_extraction import text

In [50]:
# CountVectorizer odstrani 'stopwords' in ustvari nenegativno matriko, na (i, j)-tem mestu
# imamo pojavitev besede i v j-tem dokumentu (glej zapiske na tablici)


# vzamemo 49/50 knjig, eno bomo potem poskusali uvrstiti med žanre
filepaths = glob.glob(r'C:\Users\mokro\Desktop\diploma\dipl_data\knjige_opisi\*.txt')
# min_df=2, max_df=0.9 odstranita redke in pogoste besede, to uniči celoten rezultat
custom_stopwords = list(text.ENGLISH_STOP_WORDS.union({'book', 'novel', 'story', 'author', 'character',
                                                  'edition', 'classic', 'bestseller', 'review',
                                                  'read', 'reader', 'york', 'times', 'new'}))
vectorizer= CountVectorizer(stop_words= 'english', #custom_stopwords, 
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=1, 
                            max_df=0.8)

In [51]:
X = vectorizer.fit_transform(filepaths) 


c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['far', 'make', 'u'] not in stop_words.
  warnings.warn(


In [52]:
print(X)

# malo lepše, prikaz
dense_matrix = X.toarray()
print(dense_matrix)

#še lepše
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(dense_matrix, columns=feature_names)
print(df.head())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3007 stored elements and shape (49, 1819)>
  Coords	Values
  (0, 965)	1
  (0, 1293)	1
  (0, 778)	1
  (0, 1748)	2
  (0, 1141)	1
  (0, 612)	2
  (0, 1463)	1
  (0, 136)	2
  (0, 174)	2
  (0, 1753)	1
  (0, 1600)	1
  (0, 1186)	1
  (0, 1098)	1
  (0, 1788)	1
  (0, 487)	1
  (0, 1734)	1
  (0, 640)	1
  (0, 1097)	1
  (0, 244)	1
  (0, 445)	1
  (0, 1068)	1
  (0, 1525)	1
  (0, 951)	1
  (0, 1060)	1
  (0, 1083)	1
  :	:
  (48, 420)	2
  (48, 516)	1
  (48, 1484)	1
  (48, 504)	1
  (48, 1815)	1
  (48, 716)	1
  (48, 1796)	1
  (48, 309)	1
  (48, 422)	1
  (48, 792)	1
  (48, 638)	1
  (48, 1187)	1
  (48, 1635)	1
  (48, 360)	1
  (48, 1394)	1
  (48, 1705)	1
  (48, 511)	1
  (48, 1769)	1
  (48, 1088)	1
  (48, 107)	1
  (48, 1416)	1
  (48, 281)	1
  (48, 775)	1
  (48, 1154)	1
  (48, 16)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
   abandon  abductee  able  absent  absolutely  access 

In [53]:
def nmf(X, k, max_iter=500, tol=1e-4, random_state=42):
    """
    Nenegativna matrična faktorizacija, ki uporablja pravila za posodobitev elementov na podlagi množenja.

    Parametri:
    -----------
    X : ndarray (m x n)
        Nenegativna matrika
    k : int
        Število komponent (teme/ žanri)
    max_iter : int
        Maksimalno število iteracij
    tol : float
        Toleranca konvergence (izračunano s pomočjo reconstruction error)
    random_state : int
        

    Vrne:
    --------
    W : ndarray (m x k)
    H : ndarray (k x n)
    errors : list
        Reconstruction error za vsako iteracijo
    """
    
    np.random.seed(random_state)
    
    m, n = X.shape
    
    #zacnemo z nakljucnimi nenegativnimi vrednostmi
    W = np.random.rand(m, k)
    H = np.random.rand(k, n)
    
    eps = 1e-9
    errors = []
    
    for i in range(max_iter):
        
        # posodabljanje H
        H *= (W.T @ X) / (W.T @ W @ H + eps) # + eps, da ne delimo z 0
        # posodabljanje W
        W *= (X @ H.T) / (W @ (H @ H.T) + eps)
        
        # reconstruction error
        error = np.linalg.norm(X - W @ H, 'fro')
        errors.append(error)
        
        # konvergenca
        if i > 0 and abs(errors[-2] - error) < tol:
            break
    return W, H, errors

In [54]:
# test na 'slabem' datasetu

W, H, errors = nmf(X, 4)
print(errors)
#print(W)
#print(H)

[np.float64(63.936149005427886), np.float64(62.91325990688161), np.float64(62.14875580125062), np.float64(61.48284806242411), np.float64(60.91001501542053), np.float64(60.426838257082416), np.float64(60.03249659415772), np.float64(59.69550939869473), np.float64(59.38716349501277), np.float64(59.121183799053654), np.float64(58.887100635563705), np.float64(58.73303024570335), np.float64(58.633812778865), np.float64(58.56415984256872), np.float64(58.51777261835986), np.float64(58.48789003736735), np.float64(58.469316710483), np.float64(58.454478599005874), np.float64(58.445655316006224), np.float64(58.44013905380048), np.float64(58.434640686440225), np.float64(58.420489676305415), np.float64(58.4161468906835), np.float64(58.412897741045654), np.float64(58.41000253194838), np.float64(58.40747534658902), np.float64(58.40529230881368), np.float64(58.40327915997509), np.float64(58.401247789826684), np.float64(58.399078074921015), np.float64(58.39670275411601), np.float64(58.39406813375219), n

In [56]:
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(H):
    top_words = [feature_names[i] for i in topic.argsort()[-15:]]
    print(f"Tema {topic_idx+1}: {' '.join(top_words)}")

Tema 1: time student wizarding school life death series wizard world dark lord potter voldemort hogwarts harry
Tema 2: mean death love turn novel gale rebellion win everdeen district capitol hunger game peeta katniss
Tema 3: business new force cover paris priory curator clue secret work neveu langdon code vinci da
Tema 4: make vonnegut reader war new year life love book world edition classic story time novel
