In [57]:
from sklearn.feature_extraction.text import CountVectorizer
import glob
import pandas as pd
import nltk
import numpy as np
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk import pos_tag

In [58]:
# modeli za ustrezno obdelavo stavkov, besed, ločil....
nltk.download('punkt')     # stavki, besede
nltk.download('wordnet') #lemmatizacija
nltk.download('averaged_perceptron_tagger') #POS tagganje
nltk.download('omw-1.4') 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [59]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [60]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [61]:
# tokenization and lemmatization 
lemmatizer= WordNetLemmatizer()

In [62]:
# pokupčkamo besede s podobnim korenom, pomenom skupaj
# run, runs, running -> run
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('RB'):
        return wordnet.ADV
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    else:
        return wordnet.NOUN

In [63]:
def tokenize_lematize(tekst):
    tokens = word_tokenize(tekst.lower())  # vse besede pišemo z malo začetnico
    tagged = pos_tag(tokens)
    return [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged
        if word.isalpha()    # znebimo se ločil, st,...
    ]

In [64]:
from sklearn.feature_extraction import text

In [83]:
# CountVectorizer odstrani 'stopwords' in ustvari nenegativno matriko, na (i, j)-tem mestu
# imamo pojavitev besede i v j-tem dokumentu (glej zapiske na tablici)


# vzamemo 49/50 knjig, eno bomo potem poskusali uvrstiti med žanre
filepaths = glob.glob(r'C:\Users\mokro\Desktop\diploma\dipl_data\knjige_opisi\*.txt')
# min_df=2, max_df=0.9 odstranita redke in pogoste besede, to uniči celoten rezultat
custom_stopwords = list(text.ENGLISH_STOP_WORDS.union({'book', 'novel', 'story', 'author', 'character',
                                                  'edition', 'classic', 'bestseller', 'review',
                                                  'read', 'reader', 'york', 'times', 'new'}))
vectorizer= CountVectorizer(stop_words= 'english', #custom_stopwords, 
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=2, 
                            max_df=10)

In [84]:
X = vectorizer.fit_transform(filepaths) 


c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['far', 'make', 'u'] not in stop_words.
  warnings.warn(


In [85]:
print(X)

# malo lepše, prikaz
dense_matrix = X.toarray()
print(dense_matrix)

#še lepše
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(dense_matrix, columns=feature_names)
print(df.head())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1508 stored elements and shape (49, 493)>
  Coords	Values
  (0, 265)	1
  (0, 348)	1
  (0, 469)	2
  (0, 161)	2
  (0, 44)	2
  (0, 472)	1
  (0, 431)	1
  (0, 315)	1
  (0, 485)	1
  (0, 125)	1
  (0, 170)	1
  (0, 118)	1
  (0, 263)	1
  (0, 290)	1
  (0, 338)	1
  (0, 7)	1
  (0, 369)	1
  (0, 405)	1
  (0, 325)	1
  (0, 216)	1
  (0, 214)	1
  (0, 185)	1
  (0, 424)	1
  (0, 355)	1
  (0, 26)	1
  :	:
  (48, 224)	1
  (48, 379)	1
  (48, 395)	1
  (48, 318)	2
  (48, 362)	1
  (48, 256)	1
  (48, 303)	1
  (48, 104)	1
  (48, 215)	1
  (48, 103)	1
  (48, 195)	1
  (48, 388)	1
  (48, 310)	1
  (48, 30)	2
  (48, 203)	1
  (48, 119)	1
  (48, 80)	1
  (48, 462)	1
  (48, 176)	2
  (48, 357)	1
  (48, 114)	1
  (48, 241)	1
  (48, 127)	1
  (48, 28)	1
  (48, 389)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
   acclaim  achieve  achievement  act  action  adult  adventure  affair  \
0        0   

In [93]:
def nmf(X, k, max_iter=500, tol=1e-4, random_state=42):
    """
    Nenegativna matrična faktorizacija, ki uporablja pravila za posodobitev elementov na podlagi množenja.

    Parametri:
    -----------
    X : ndarray (m x n)
        Nenegativna matrika
    k : int
        Število komponent (teme/ žanri)
    max_iter : int
        Maksimalno število iteracij
    tol : float
        Toleranca konvergence (izračunano s pomočjo reconstruction error)
    random_state : int
        

    Vrne:
    --------
    W : ndarray (m x k)
    H : ndarray (k x n)
    errors : list
        Reconstruction error za vsako iteracijo
    """
    
    np.random.seed(random_state)
    
    m, n = X.shape
    
    #zacnemo z nakljucnimi nenegativnimi vrednostmi
    W = np.random.rand(m, k)
    H = np.random.rand(k, n)
    
    eps = 1e-9
    errors = []
    
    for i in range(max_iter):
        
        # posodabljanje H
        H *= (W.T @ X) / (W.T @ W @ H + eps) # + eps, da ne delimo z 0
        # posodabljanje W
        W *= (X @ H.T) / (W @ (H @ H.T) + eps)
        
        # reconstruction error
        error = np.linalg.norm(X - W @ H, 'fro')
        errors.append(error)
        
        # konvergenca
        if i > 0 and abs(errors[-2] - error) < tol:
            break
    return W, H, errors

In [87]:
# test na 'slabem' datasetu

W, H, errors = nmf(X, 4)
print(errors)
#print(W)
#print(H)

[np.float64(44.68544155358993), np.float64(43.3630552724958), np.float64(42.471188856567), np.float64(41.66004730520838), np.float64(41.06994053981362), np.float64(40.65218595865828), np.float64(40.36387297296632), np.float64(40.172197543334605), np.float64(40.04302149061008), np.float64(39.95500599191357), np.float64(39.894596189169654), np.float64(39.850406966227816), np.float64(39.81662523379946), np.float64(39.78795144015718), np.float64(39.7619399167241), np.float64(39.73647430220727), np.float64(39.71004759290556), np.float64(39.68198472733529), np.float64(39.6521640528067), np.float64(39.62186816687712), np.float64(39.59201645469918), np.float64(39.56000174770301), np.float64(39.535986123394046), np.float64(39.519322679499496), np.float64(39.506506193228496), np.float64(39.49823738877129), np.float64(39.488868784081724), np.float64(39.483765845554764), np.float64(39.477776309785604), np.float64(39.47130445627945), np.float64(39.467689981228624), np.float64(39.46416006101509), np

In [ ]:
# iskanje najbolj ugodne kombinacije min_df in max_df

min_dfs = [2, 3, 4, 5]

results = []

for min_df in min_dfs:
        vectorizer= CountVectorizer(stop_words= 'english',  
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=min_df)
        X = vectorizer.fit_transform(filepaths)

        W, H, errors = nmf(X, 4)
        results.append({
            "min_df": min_df,
            "error": errors[-1],
            "n_features": X.shape[1]
            
        })
        feature_names = vectorizer.get_feature_names_out()
        for topic_idx, topic in enumerate(H):
            top_words = [feature_names[i] for i in topic.argsort()[-15:]]
            print(f"Tema {topic_idx+1}: {' '.join(top_words)}")
            
for r in results:
    print(r)
       

c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['far', 'make', 'u'] not in stop_words.
  warnings.warn(


Tema 1: journey evil forge darkness make young face hobbit rule power lord dark bilbo baggins ring
Tema 2: cruel second novel turn love rebellion mean death win everdeen district hunger capitol game katniss
Tema 3: note tale war reader year new life book world love edition classic story time novel
Tema 4: time student wizarding school life death series wizard dark world lord potter voldemort hogwarts harry
Tema 1: book wizarding death begin learn witchcraft wizardry wizard world school series life potter hogwarts harry
Tema 2: woman family friendship power best new reader young tell classic time life love story novel
Tema 3: library cover fiction introduction note make literature american year classic war time book world edition
Tema 4: open just grow return wizard hogwarts world death strong student time dark lord voldemort harry
Tema 1: mean place story begin learn face series young friendship book family world death love life
Tema 2: century father boy tale power york best tell love

In [88]:
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(H):
    top_words = [feature_names[i] for i in topic.argsort()[-15:]]
    print(f"Tema {topic_idx+1}: {' '.join(top_words)}")

Tema 1: forge tell journey remain age young face hobbit rule power dark lord baggins bilbo ring
Tema 2: suzanne collins cruel second turn rebellion mean death win everdeen hunger district capitol game katniss
Tema 3: introduction woman force fiction american man cover young make alternate tale note war jane book
Tema 4: turn evil friend student wizarding school death series dark wizard lord potter voldemort hogwarts harry
