In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import glob
import pandas as pd
import nltk
import numpy as np
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk import pos_tag

In [2]:
# modeli za ustrezno obdelavo stavkov, besed, ločil....
nltk.download('punkt')     # stavki, besede
nltk.download('wordnet') #lemmatizacija
nltk.download('averaged_perceptron_tagger') #POS tagganje
nltk.download('omw-1.4') 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [3]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [4]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [5]:
# tokenization and lemmatization 
lemmatizer= WordNetLemmatizer()

In [6]:
# pokupčkamo besede s podobnim korenom, pomenom skupaj
# run, runs, running -> run
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('RB'):
        return wordnet.ADV
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    else:
        return wordnet.NOUN

In [7]:
def tokenize_lematize(tekst):
    tokens = word_tokenize(tekst.lower())  # vse besede pišemo z malo začetnico
    tagged = pos_tag(tokens)
    return [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged
        if word.isalpha()    # znebimo se ločil, st,...
    ]

In [8]:
# CountVectorizer odstrani 'stopwords' in ustvari nenegativno matriko, na (i, j)-tem mestu
# imamo pojavitev besede i v j-tem dokumentu (glej zapiske na tablici)


# vzamemo 49/50 knjig, eno bomo potem poskusali uvrstiti med žanre
filepaths = glob.glob(r'C:\Users\mokro\Desktop\diploma\dipl_data\knjige_opisi\*.txt')
# min_df=2, max_df=0.9 odstranita redke in pogoste besede, to uniči celoten rezultat
vectorizer= CountVectorizer(stop_words='english', 
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=2, 
                            max_df=0.9)

In [9]:
X = vectorizer.fit_transform(filepaths) 


c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['far', 'make', 'u'] not in stop_words.
  warnings.warn(


In [10]:
print(X)

# malo lepše, prikaz
dense_matrix = X.toarray()
print(dense_matrix)

#še lepše
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(dense_matrix, columns=feature_names)
print(df.head())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1692 stored elements and shape (49, 504)>
  Coords	Values
  (0, 269)	1
  (0, 355)	1
  (0, 478)	2
  (0, 163)	2
  (0, 44)	2
  (0, 481)	1
  (0, 439)	1
  (0, 321)	1
  (0, 494)	1
  (0, 127)	1
  (0, 172)	1
  (0, 69)	1
  (0, 119)	1
  (0, 293)	1
  (0, 415)	1
  (0, 267)	1
  (0, 296)	1
  (0, 344)	1
  (0, 262)	1
  (0, 7)	1
  (0, 496)	1
  (0, 376)	1
  (0, 412)	1
  (0, 331)	1
  (0, 218)	1
  :	:
  (48, 226)	1
  (48, 386)	1
  (48, 402)	1
  (48, 324)	2
  (48, 369)	1
  (48, 259)	1
  (48, 309)	1
  (48, 105)	1
  (48, 217)	1
  (48, 104)	1
  (48, 197)	1
  (48, 395)	1
  (48, 316)	1
  (48, 30)	2
  (48, 205)	1
  (48, 120)	1
  (48, 81)	1
  (48, 471)	1
  (48, 178)	2
  (48, 364)	1
  (48, 115)	1
  (48, 243)	1
  (48, 129)	1
  (48, 28)	1
  (48, 396)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]
   acclaim  achieve  achievement  act  action  adult  adventure  affair  \
0        0   

In [ ]:
# implementacija nmf


#def nmf(X, k, eps):
#    n, m = len(X), len(X[0])
#
#    W = np.random.rand(m, k)
#    H = np.random.rand(k,n)
#
#    H *= (W.T @ X) / (W.T @ W @ H + eps)
#    W *= (X @ H.T) / (W @ H @ H.T + eps)



In [ ]:
def nmf(X, k, max_iter=500, tol=1e-4, random_state=42):
    """
    Nenegativna matrična faktorizacija, ki uporablja pravila za posodobitev elementov na podlagi množenja.

    Parametri:
    -----------
    X : ndarray (m x n)
        Nenegativna matrika
    k : int
        Stevilo komponent (teme/ žanri)
    max_iter : int
        Maksimalno število iteracij
    tol : float
        Toleranca konvergence (izračunano s pomočjo reconstruction error)
    random_state : int
        

    Vrne:
    --------
    W : ndarray (m x k)
    H : ndarray (k x n)
    errors : list
        Reconstruction za vsako iteracijo
    """
    
    np.random.seed(random_state)
    
    m, n = X.shape
    
    #zacnemo z nakljucnimi nenegativnimi vrednostmi
    W = np.random.rand(m, k)
    H = np.random.rand(k, n)
    
    eps = 1e-9
    errors = []
    
    for i in range(max_iter):
        
        # posodabljanje H
        H *= (W.T @ X) / (W.T @ W @ H + eps) # + eps, da ne delimo z 0
        # posodabljanje W
        W *= (X @ H.T) / (W @ (H @ H.T) + eps)
        
        # reconstruction error
        error = np.linalg.norm(X - W @ H, 'fro')
        errors.append(error)
        
        # konvergenca
        if i > 0 and abs(errors[-2] - error) < tol:
            break
    
    return W, H, errors

In [18]:
# test na 'slabe' datasetu

W, H, errors = nmf(X, 4)
print(errors)
#print(W)
#print(H)

[np.float64(47.589757567223685), np.float64(46.5312856684237), np.float64(45.541493657818314), np.float64(44.491307013779895), np.float64(43.77033220271467), np.float64(43.381007192784885), np.float64(43.154102365320114), np.float64(43.004724126114596), np.float64(42.891291219811364), np.float64(42.79447498077632), np.float64(42.707634338834794), np.float64(42.62573864827638), np.float64(42.54412076548579), np.float64(42.461296080023054), np.float64(42.37982099056631), np.float64(42.304735570833635), np.float64(42.24286828011119), np.float64(42.194751985684164), np.float64(42.15873237379664), np.float64(42.13146648884493), np.float64(42.109538547338786), np.float64(42.096730298233204), np.float64(42.08758238840301), np.float64(42.0813278326032), np.float64(42.07688020136935), np.float64(42.07318161497579), np.float64(42.06984629950478), np.float64(42.06697012205353), np.float64(42.06501940478492), np.float64(42.063828056027226), np.float64(42.06299040067564), np.float64(42.062326232548

In [17]:
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(H):
    top_words = [feature_names[i] for i in topic.argsort()[-10:]]
    print(f"Tema {topic_idx}: {' '.join(top_words)}")

Tema 0: young face hobbit rule power lord dark bilbo baggins ring
Tema 1: rebellion mean death win everdeen district hunger capitol game katniss
Tema 2: new life book world love edition classic story time novel
Tema 3: death series wizard dark world lord potter voldemort hogwarts harry
