In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import glob
import pandas as pd
import nltk
import numpy as np
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk import pos_tag

In [2]:
# modeli za ustrezno obdelavo stavkov, besed, ločil....
nltk.download('punkt')     # stavki, besede
nltk.download('wordnet') #lemmatizacija
nltk.download('averaged_perceptron_tagger') #POS tagganje
nltk.download('omw-1.4') 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [3]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [4]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [5]:
# tokenization and lemmatization 
lemmatizer= WordNetLemmatizer()

In [6]:
# pokupčkamo besede s podobnim korenom, pomenom skupaj
# run, runs, running -> run
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('RB'):
        return wordnet.ADV
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    else:
        return wordnet.NOUN

In [7]:
def tokenize_lematize(tekst):
    tokens = word_tokenize(tekst.lower())  # vse besede pišemo z malo začetnico
    tagged = pos_tag(tokens)
    return [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged
        if word.isalpha()    # znebimo se ločil, st,...
    ]

In [8]:
import random
from sklearn.feature_extraction import text

In [48]:
# CountVectorizer odstrani 'stopwords' in ustvari nenegativno matriko, na (i, j)-tem mestu
# imamo pojavitev besede i v j-tem dokumentu (glej zapiske na tablici)

#random.seed(42)
# vzamemo 150/200 knjig, ostale bomo potem poskusali uvrstiti med žanre
filepaths = glob.glob(r'C:\Users\mokro\Desktop\diploma\najbolj_popularne\najboljse_knjige_opisi\*.txt')[:250]
#filepaths= random.sample(filepaths, 150)
# min_df=2, max_df=0.9 odstranita redke in pogoste besede, to uniči celoten rezultat
custom_stopwords = list(text.ENGLISH_STOP_WORDS.union({'book', 'novel', 'story', 'author', 'character',
                                                  'edition', 'classic', 'bestseller', 'review',
                                                  'read', 'reader', 'york', 'times', 'new'}))
vectorizer= CountVectorizer(stop_words=custom_stopwords, 
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=1, 
                            max_df=0.9)

In [49]:
X = vectorizer.fit_transform(filepaths) 


c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['far', 'make', 'time', 'u'] not in stop_words.
  warnings.warn(


In [50]:
print(X)

# malo lepše, prikaz
dense_matrix = X.toarray()
print(dense_matrix)

#še lepše
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(dense_matrix, columns=feature_names)
print(df.head())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14487 stored elements and shape (250, 5570)>
  Coords	Values
  (0, 5469)	2
  (0, 3094)	3
  (0, 1766)	1
  (0, 1927)	1
  (0, 2934)	1
  (0, 752)	1
  (0, 1187)	3
  (0, 2371)	2
  (0, 2003)	3
  (0, 416)	1
  (0, 4239)	1
  (0, 3680)	2
  (0, 2770)	1
  (0, 3387)	1
  (0, 149)	1
  (0, 2867)	1
  (0, 3314)	1
  (0, 3531)	1
  (0, 4462)	1
  (0, 685)	2
  (0, 4813)	1
  (0, 3492)	1
  (0, 1370)	2
  (0, 2205)	1
  (0, 1100)	1
  :	:
  (249, 5538)	1
  (249, 1347)	1
  (249, 199)	1
  (249, 3568)	1
  (249, 1769)	1
  (249, 4347)	1
  (249, 1337)	1
  (249, 977)	1
  (249, 5111)	1
  (249, 2831)	1
  (249, 514)	1
  (249, 4584)	1
  (249, 1338)	1
  (249, 3288)	1
  (249, 4468)	1
  (249, 95)	1
  (249, 1019)	1
  (249, 1521)	1
  (249, 791)	1
  (249, 4894)	1
  (249, 1496)	1
  (249, 2887)	1
  (249, 837)	2
  (249, 2696)	2
  (249, 2765)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
   aaron  abag

In [51]:
def nmf(X, k, max_iter=500, tol=1e-4, random_state=42):
    """
    Nenegativna matrična faktorizacija, ki uporablja pravila za posodobitev elementov na podlagi množenja.

    Parametri:
    -----------
    X : ndarray (m x n)
        Nenegativna matrika
    k : int
        Stevilo komponent (teme/ žanri)
    max_iter : int
        Maksimalno število iteracij
    tol : float
        Toleranca konvergence (izračunano s pomočjo reconstruction error)
    random_state : int
        

    Vrne:
    --------
    W : ndarray (m x k)
    H : ndarray (k x n)
    errors : list
        Reconstruction za vsako iteracijo
    """
    
    np.random.seed(random_state)
    
    m, n = X.shape
    
    #zacnemo z nakljucnimi nenegativnimi vrednostmi
    W = np.random.rand(m, k)
    H = np.random.rand(k, n)
    
    eps = 1e-9
    errors = []
    
    for i in range(max_iter):
        
        # posodabljanje H
        H *= (W.T @ X) / (W.T @ W @ H + eps) # + eps, da ne delimo z 0
        # posodabljanje W
        W *= (X @ H.T) / (W @ (H @ H.T) + eps)
        
        # reconstruction error
        error = np.linalg.norm(X - W @ H, 'fro')
        errors.append(error)
        
        # konvergenca
        if i > 0 and abs(errors[-2] - error) < tol:
            break

    return W, H, errors

In [52]:
# test 

W, H, errors = nmf(X, 4)
print(errors)
#print(W)
#print(H)

[np.float64(147.06482517560937), np.float64(146.48239785992715), np.float64(145.97986197940722), np.float64(145.48522652024513), np.float64(145.0953980245757), np.float64(144.78768097252214), np.float64(144.52192663528257), np.float64(144.2879065819503), np.float64(144.09202707233052), np.float64(143.94024534821335), np.float64(143.82838695932267), np.float64(143.74638971635926), np.float64(143.6845525285778), np.float64(143.6362956122521), np.float64(143.5978678166354), np.float64(143.56646192035666), np.float64(143.53858837994235), np.float64(143.513255158877), np.float64(143.49138738827207), np.float64(143.4720768826994), np.float64(143.4535086871057), np.float64(143.43417314140547), np.float64(143.41603161467225), np.float64(143.40126830008532), np.float64(143.38879340828674), np.float64(143.37753608962586), np.float64(143.36710041155033), np.float64(143.3579827275094), np.float64(143.3495188688398), np.float64(143.34143762071764), np.float64(143.3335075348511), np.float64(143.3265

In [ ]:
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(H):
    top_words = [feature_names[i] for i in topic.argsort()[-15:]]
    print(f"Tema {topic_idx+1}: {' '.join(top_words)}")

Tema 0: wicked island bear room leave chop devon seven rhyme hang guest sit murder boy little
Tema 1: dragomir time academy world protect life make vampire dimitri best friend strigoi love lissa rise
Tema 2: adventure tournament time world series turn student wizard dark school lord potter voldemort hogwarts harry
Tema 3: sister man young make tell work girl family know year woman world time love life
