In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import glob
import pandas as pd
import nltk
import numpy as np
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk import pos_tag

In [2]:
# modeli za ustrezno obdelavo stavkov, besed, ločil....
nltk.download('punkt')     # stavki, besede
nltk.download('wordnet') #lemmatizacija
nltk.download('averaged_perceptron_tagger') #POS tagganje
nltk.download('omw-1.4') 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [3]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [4]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [5]:
# tokenization and lemmatization 
lemmatizer= WordNetLemmatizer()

In [6]:
# pokupčkamo besede s podobnim korenom, pomenom skupaj
# run, runs, running -> run
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('RB'):
        return wordnet.ADV
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    else:
        return wordnet.NOUN

In [7]:
def tokenize_lematize(tekst):
    tokens = word_tokenize(tekst.lower())  # vse besede pišemo z malo začetnico
    tagged = pos_tag(tokens)
    return [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged
        if word.isalpha()    # znebimo se ločil, st,...
    ]

In [8]:
import random
from sklearn.feature_extraction import text

In [ ]:
# CountVectorizer odstrani 'stopwords' in ustvari nenegativno matriko, na (i, j)-tem mestu
# imamo pojavitev besede i v j-tem dokumentu (glej zapiske na tablici)

#random.seed(42)
# vzamemo 150/200 knjig, ostale bomo potem poskusali uvrstiti med žanre
filepaths = glob.glob(r'C:\Users\mokro\Desktop\diploma\najbolj_popularne\najboljse_knjige_opisi\*.txt')[:250]
#filepaths= random.sample(filepaths, 150)
# min_df=2, max_df=0.9 odstranita redke in pogoste besede, to uniči celoten rezultat
custom_stopwords = list(text.ENGLISH_STOP_WORDS.union({'book', 'novel', 'story', 'author', 'character',
                                                  'edition', 'classic', 'bestseller', 'review',
                                                  'read', 'reader', 'york', 'times', 'new'}))
vectorizer= CountVectorizer(stop_words=custom_stopwords, 
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=1, 
                            max_df=0.8)

In [10]:
X = vectorizer.fit_transform(filepaths) 


c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['far', 'make', 'time', 'u'] not in stop_words.
  warnings.warn(


In [11]:
print(X)

# malo lepše, prikaz
dense_matrix = X.toarray()
print(dense_matrix)

#še lepše
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(dense_matrix, columns=feature_names)
print(df.head())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11105 stored elements and shape (250, 2188)>
  Coords	Values
  (0, 2147)	2
  (0, 1216)	3
  (0, 685)	1
  (0, 757)	1
  (0, 1164)	1
  (0, 266)	1
  (0, 458)	3
  (0, 950)	2
  (0, 787)	3
  (0, 155)	1
  (0, 1652)	1
  (0, 1420)	2
  (0, 1093)	1
  (0, 1314)	1
  (0, 57)	1
  (0, 1129)	1
  (0, 1288)	1
  (0, 1367)	1
  (0, 239)	2
  (0, 1889)	1
  (0, 529)	2
  (0, 875)	1
  (0, 423)	1
  (0, 1138)	1
  (0, 744)	1
  :	:
  (249, 1316)	1
  (249, 1249)	1
  (249, 2181)	1
  (249, 526)	1
  (249, 77)	1
  (249, 1386)	1
  (249, 687)	1
  (249, 1692)	1
  (249, 519)	1
  (249, 362)	1
  (249, 2019)	1
  (249, 1114)	1
  (249, 189)	1
  (249, 1786)	1
  (249, 520)	1
  (249, 1284)	1
  (249, 1740)	1
  (249, 40)	1
  (249, 382)	1
  (249, 587)	1
  (249, 283)	1
  (249, 1917)	1
  (249, 578)	1
  (249, 1139)	1
  (249, 301)	2
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
   abandon  abducts  abide  able

In [12]:
def nmf(X, k, max_iter=500, tol=1e-4, random_state=42):
    """
    Nenegativna matrična faktorizacija, ki uporablja pravila za posodobitev elementov na podlagi množenja.

    Parametri:
    -----------
    X : ndarray (m x n)
        Nenegativna matrika
    k : int
        Stevilo komponent (teme/ žanri)
    max_iter : int
        Maksimalno število iteracij
    tol : float
        Toleranca konvergence (izračunano s pomočjo reconstruction error)
    random_state : int
        

    Vrne:
    --------
    W : ndarray (m x k)
    H : ndarray (k x n)
    errors : list
        Reconstruction za vsako iteracijo
    """
    
    np.random.seed(random_state)
    
    m, n = X.shape
    
    #zacnemo z nakljucnimi nenegativnimi vrednostmi
    W = np.random.rand(m, k)
    H = np.random.rand(k, n)
    
    eps = 1e-9
    errors = []
    
    for i in range(max_iter):
        
        # posodabljanje H
        H *= (W.T @ X) / (W.T @ W @ H + eps) # + eps, da ne delimo z 0
        # posodabljanje W
        W *= (X @ H.T) / (W @ (H @ H.T) + eps)
        
        # reconstruction error
        error = np.linalg.norm(X - W @ H, 'fro')
        errors.append(error)
        
        # konvergenca
        if i > 0 and abs(errors[-2] - error) < tol:
            break

    return W, H, errors

In [13]:
# test 

W, H, errors = nmf(X, 4)
print(errors)
#print(W)
#print(H)

[np.float64(126.38136192894429), np.float64(125.88319911073131), np.float64(125.50215365398044), np.float64(125.06445738936624), np.float64(124.60947372136877), np.float64(124.19558288757952), np.float64(123.84317611283949), np.float64(123.55962180507258), np.float64(123.34151528287953), np.float64(123.16771302885458), np.float64(123.01967438788562), np.float64(122.88984085643729), np.float64(122.77671977095989), np.float64(122.67956268884923), np.float64(122.59783541609664), np.float64(122.53037269873475), np.float64(122.47498044345647), np.float64(122.4277360241762), np.float64(122.38556052966209), np.float64(122.34917041450485), np.float64(122.31731550777384), np.float64(122.28936717184142), np.float64(122.2653275988314), np.float64(122.24456088642877), np.float64(122.22722391995116), np.float64(122.21287349085853), np.float64(122.20074465142484), np.float64(122.19006462983931), np.float64(122.18055360196574), np.float64(122.17221780282276), np.float64(122.16496044248576), np.float6

In [ ]:
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(H):
    top_words = [feature_names[i] for i in topic.argsort()[-15:]]
    print(f"Tema {topic_idx}: {' '.join(top_words)}")

Tema 0: room leave seven rhyme hang guest sit murder boy little
Tema 1: life make dimitri vampire best friend love strigoi lissa rise
Tema 2: work girl family know year woman world time love life
Tema 3: turn student wizard school dark lord potter voldemort hogwarts harry
