In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import glob
import pandas as pd
import nltk
import numpy as np
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk import pos_tag

In [2]:
# modeli za ustrezno obdelavo stavkov, besed, ločil....
nltk.download('punkt')     # stavki, besede
nltk.download('wordnet') #lemmatizacija
nltk.download('averaged_perceptron_tagger') #POS tagganje
nltk.download('omw-1.4') 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [3]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [4]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [5]:
# tokenization and lemmatization 
lemmatizer= WordNetLemmatizer()

In [6]:
# pokupčkamo besede s podobnim korenom, pomenom skupaj
# run, runs, running -> run
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('RB'):
        return wordnet.ADV
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    else:
        return wordnet.NOUN

In [7]:
def tokenize_lematize(tekst):
    tokens = word_tokenize(tekst.lower())  # vse besede pišemo z malo začetnico
    tagged = pos_tag(tokens)
    return [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged
        if word.isalpha()    # znebimo se ločil, st,...
    ]

In [8]:
import random

In [18]:
# CountVectorizer odstrani 'stopwords' in ustvari nenegativno matriko, na (i, j)-tem mestu
# imamo pojavitev besede i v j-tem dokumentu (glej zapiske na tablici)

#random.seed(42)
# vzamemo 150/200 knjig, ostale bomo potem poskusali uvrstiti med žanre
filepaths = glob.glob(r'C:\Users\mokro\Desktop\diploma\najbolj_popularne\najboljse_knjige_opisi\*.txt')[:250]
#filepaths= random.sample(filepaths, 150)
# min_df=2, max_df=0.9 odstranita redke in pogoste besede, to uniči celoten rezultat
vectorizer= CountVectorizer(stop_words='english', 
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=2, 
                            max_df=0.9)

In [19]:
X = vectorizer.fit_transform(filepaths) 


c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['far', 'make', 'u'] not in stop_words.
  warnings.warn(


In [20]:
print(X)

# malo lepše, prikaz
dense_matrix = X.toarray()
print(dense_matrix)

#še lepše
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(dense_matrix, columns=feature_names)
print(df.head())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11629 stored elements and shape (250, 2201)>
  Coords	Values
  (0, 2159)	2
  (0, 1222)	3
  (0, 691)	1
  (0, 763)	1
  (0, 1170)	1
  (0, 269)	1
  (0, 463)	3
  (0, 956)	2
  (0, 793)	3
  (0, 156)	1
  (0, 1663)	1
  (0, 1428)	2
  (0, 1099)	1
  (0, 1321)	1
  (0, 57)	1
  (0, 1135)	1
  (0, 1294)	1
  (0, 1375)	1
  (0, 242)	2
  (0, 1901)	1
  (0, 534)	2
  (0, 881)	1
  (0, 428)	1
  (0, 1144)	1
  (0, 750)	1
  :	:
  (249, 1323)	1
  (249, 1255)	1
  (249, 2193)	1
  (249, 531)	1
  (249, 77)	1
  (249, 1394)	1
  (249, 693)	1
  (249, 1703)	1
  (249, 524)	1
  (249, 367)	1
  (249, 2031)	1
  (249, 1120)	1
  (249, 191)	1
  (249, 1797)	1
  (249, 525)	1
  (249, 1290)	1
  (249, 1751)	1
  (249, 40)	1
  (249, 387)	1
  (249, 593)	1
  (249, 287)	1
  (249, 1929)	1
  (249, 583)	1
  (249, 1145)	1
  (249, 305)	2
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
   abandon  abducts  abide  able

In [21]:
def nmf(X, k, max_iter=500, tol=1e-4, random_state=42):
    """
    Nenegativna matrična faktorizacija, ki uporablja pravila za posodobitev elementov na podlagi množenja.

    Parametri:
    -----------
    X : ndarray (m x n)
        Nenegativna matrika
    k : int
        Stevilo komponent (teme/ žanri)
    max_iter : int
        Maksimalno število iteracij
    tol : float
        Toleranca konvergence (izračunano s pomočjo reconstruction error)
    random_state : int
        

    Vrne:
    --------
    W : ndarray (m x k)
    H : ndarray (k x n)
    errors : list
        Reconstruction za vsako iteracijo
    """
    
    np.random.seed(random_state)
    
    m, n = X.shape
    
    #zacnemo z nakljucnimi nenegativnimi vrednostmi
    W = np.random.rand(m, k)
    H = np.random.rand(k, n)
    
    eps = 1e-9
    errors = []
    
    for i in range(max_iter):
        
        # posodabljanje H
        H *= (W.T @ X) / (W.T @ W @ H + eps) # + eps, da ne delimo z 0
        # posodabljanje W
        W *= (X @ H.T) / (W @ (H @ H.T) + eps)
        
        # reconstruction error
        error = np.linalg.norm(X - W @ H, 'fro')
        errors.append(error)
        
        # konvergenca
        if i > 0 and abs(errors[-2] - error) < tol:
            break

    return W, H, errors

In [30]:
# test 

W, H, errors = nmf(X, 4)
print(errors)
#print(W)
#print(H)

[np.float64(129.93163266495674), np.float64(129.4485777707094), np.float64(129.0672580536717), np.float64(128.65884465894524), np.float64(128.2465649909972), np.float64(127.85646134493798), np.float64(127.5127290233908), np.float64(127.23267166934747), np.float64(127.01169150406865), np.float64(126.83255823729257), np.float64(126.68285469449901), np.float64(126.55405470912537), np.float64(126.43958081054649), np.float64(126.33612606407704), np.float64(126.24083698970442), np.float64(126.15152260036204), np.float64(126.06780369334435), np.float64(125.99004464234967), np.float64(125.91842739639765), np.float64(125.85321996063433), np.float64(125.79306835954387), np.float64(125.73675315281156), np.float64(125.68571030375712), np.float64(125.63978760538201), np.float64(125.59884325133065), np.float64(125.56349300304285), np.float64(125.53478419479129), np.float64(125.51177709375838), np.float64(125.4932697280622), np.float64(125.47786655351649), np.float64(125.46507245589473), np.float64(1

In [31]:
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(H):
    top_words = [feature_names[i] for i in topic.argsort()[-10:]]
    print(f"Tema {topic_idx}: {' '.join(top_words)}")

Tema 0: room rhyme leave seven hang guest sit murder boy little
Tema 1: life make vampire dimitri best friend strigoi love lissa rise
Tema 2: critical text book new publish work classic include edition novel
Tema 3: know book woman year new world love story time life
