In [1]:
#!python -m spacy download en_core_web_sm

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import glob
import pandas as pd
import nltk
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk import pos_tag
import wordcloud

In [3]:
# # modeli za ustrezno obdelavo stavkov, besed, ločil....
# nltk.download('punkt')     # stavki, besede
# nltk.download('wordnet') #lemmatizacija
# nltk.download('averaged_perceptron_tagger') #POS tagganje
# nltk.download('omw-1.4') 
# nltk.download('punkt_tab')
# nltk.download('averaged_perceptron_tagger_eng')

In [4]:
# tokenization and lemmatization 
# lemmatizer= WordNetLemmatizer()

In [5]:
# # pokupčkamo besede s podobnim korenom, pomenom skupaj
# # run, runs, running -> run
# def get_wordnet_pos(treebank_tag):
#     if treebank_tag.startswith('J'):
#         return wordnet.ADJ
#     elif treebank_tag.startswith('V'):
#         return wordnet.VERB
#     elif treebank_tag.startswith('RB'):
#         return wordnet.ADV
#     elif treebank_tag.startswith('N'):
#         return wordnet.NOUN
#     else:
#         return wordnet.NOUN

In [6]:
import spacy

nlp = spacy.load("en_core_web_sm")

In [7]:
def tokenize_lematize(tekst):
    doc = nlp(tekst)
    
    izbrane_besede = []
    
    # želimo odstraniti osebe, kraji, jeziki, narodi...
    odstrani_pos = ['PROPN', 'PRON', 'VERB', 'ADV']
    odstrani_entitete = {'PERSON', 'GPE', 'LOC', 'NORP', 'FAC', 'ORG'}
    
    #mnozica prepoznanih entitet
    for token in doc:
        # odstranimo i
        if token.pos_ in odstrani_pos:
            continue
        if token.ent_type_ in odstrani_entitete:
            continue
            
        # spacy ima oznake NOUN, ADJ
        if token.pos_ in ['NOUN']:
            beseda = token.lemma_.lower()
            # samo crke in dolžina nad 2 znaka
            if beseda.isalpha() and len(beseda) > 2:
                izbrane_besede.append(beseda)
                
    return izbrane_besede

In [8]:
base_vectorizer = CountVectorizer(stop_words='english')
base_stopwords = base_vectorizer.get_stop_words()


custom_words = {
    # založniški šum 
    'book', 'novel', 'story', 'author', 'literature', 'edition', 'seller', 
    'read', 'reader', 'page', 'chapter', 'write', 'writer', 'publish', 
    'publication', 'review', 'times', 'york', 'print', 'copy', 'best', 
    'original', 'classic', 'introduction', 'note', 'debut', 'thriller',
    'unique', 'fascinating', 'scandal', 'major', 'character', 'cover', 'magazine',
    'self', 'series', 'volume', 'masterpiece', 'translation', 'film', 'tale', 'course',
    'trilogy',
    
    # splošni opisi 
    'way', 'thing', 'important', 'practical', 'young', 'boy', 'girl', 
    'human', 'people', 'great', 'good', 'bad', 'true', 'new', 'old',
    'life', 'world', 'everything', 'day', 'time', 'year', 'make',
    'take', 'come', 'think', 'feel', 'know', 'look', 'want', 'large', 'small',
    'man', 'woman', 'literary', 'secret', 'isbn', 'mother', 'sister', 'father',
    'little', 'room', 'place', 'end', 'first', 'second', 'red', 'purple', 'black',
    
    #iz izpisa
    'professional', 'guide', 'experience', 'natural', 'vivid', 'narrative',
    'compelling', 'extraordinary', 'powerful', 'voice', 'mind', 'bestseller', 'essey', 'essay',
    'art', 'tessa', 'lissa', 'daughter', 'son', 'wife', 'brother', 'sister', 'bibliography', 'penguin', 'child'
}


all_stopwords = list(base_stopwords.union(custom_words))

In [ ]:
# CountVectorizer odstrani 'stopwords' in ustvari nenegativno matriko, na (i, j)-tem mestu število pojavitev j-te besede v i-tem dokumentu

# vzamemo le učno množico v velikosti 250 dokumentov
filepaths = glob.glob(r'C:\Users\mokro\Desktop\diploma\najbolj_popularne\naj_ang_opisi\*.txt')[:250]
vectorizer= CountVectorizer(stop_words=all_stopwords, 
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=3)

In [10]:
X = vectorizer.fit_transform(filepaths) 

c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [11]:
print(X)

# malo lepše, prikaz
dense_matrix = X.toarray()
print(dense_matrix)

#še lepše
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(dense_matrix, columns=feature_names)
print(df.head())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3272 stored elements and shape (250, 560)>
  Coords	Values
  (0, 181)	1
  (0, 120)	3
  (0, 236)	2
  (0, 187)	3
  (0, 282)	1
  (0, 12)	1
  (0, 174)	1
  (0, 486)	2
  (0, 326)	1
  (0, 77)	1
  (0, 233)	1
  (0, 290)	1
  (1, 9)	1
  (1, 183)	1
  (1, 41)	1
  (1, 48)	1
  (2, 9)	1
  (2, 366)	1
  (2, 163)	1
  (2, 61)	1
  (2, 25)	1
  (2, 242)	1
  (2, 376)	1
  (2, 167)	1
  (3, 77)	1
  :	:
  (247, 173)	1
  (247, 232)	4
  (247, 306)	1
  (247, 555)	1
  (247, 176)	1
  (247, 349)	1
  (247, 258)	1
  (247, 554)	1
  (247, 221)	1
  (247, 153)	1
  (247, 222)	1
  (247, 162)	1
  (247, 194)	1
  (247, 545)	1
  (247, 152)	1
  (248, 326)	1
  (248, 191)	2
  (248, 285)	1
  (248, 545)	1
  (249, 183)	1
  (249, 484)	3
  (249, 224)	2
  (249, 223)	2
  (249, 552)	1
  (249, 142)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
   academy  accident  acclaim  account  achievement  act  action  

In [12]:
from sklearn.decomposition import PCA

In [26]:
pca = PCA(n_components=6)  
X_pca = pca.fit_transform(X)

In [27]:
print(pca.explained_variance_ratio_)
print("Skupaj:", sum(pca.explained_variance_ratio_))

[0.0364229  0.02453223 0.02328794 0.02221593 0.01777866 0.01753395]
Skupaj: 0.14177160815251766


In [30]:
feature_names = vectorizer.get_feature_names_out()

for i, comp in enumerate(pca.components_):
    top_words = [feature_names[j] for j in comp.argsort()[-10:]]
    print(f"PC{i+1}: {top_words}")

PC1: ['war', 'devotion', 'shadowhunter', 'plan', 'death', 'king', 'strigoi', 'family', 'heart', 'love']
PC2: ['magic', 'band', 'camp', 'power', 'hogwart', 'strigoi', 'school', 'blood', 'friend', 'adventure']
PC3: ['plot', 'enemy', 'conflict', 'balance', 'dragon', 'kingdom', 'game', 'throne', 'land', 'family']
PC4: ['generation', 'chronology', 'treasure', 'band', 'work', 'text', 'height', 'case', 'love', 'adventure']
PC5: ['age', 'witchcraft', 'letter', 'summer', 'school', 'wizard', 'student', 'voldemort', 'death', 'hogwart']
PC6: ['question', 'night', 'jess', 'job', 'town', 'apartment', 'horror', 'house', 'past', 'adventure']


In [31]:
feature_names = vectorizer.get_feature_names_out()

for i, comp in enumerate(pca.components_):
    top_indices = comp.argsort()[-10:][::-1]
    top_words_with_weights = [f"{feature_names[j]} ({comp[j]:.3f})" for j in top_indices]
    
    print(f"PC{i+1}: {', '.join(top_words_with_weights)}")

PC1: love (0.852), heart (0.157), family (0.132), strigoi (0.092), king (0.083), death (0.072), plan (0.071), shadowhunter (0.068), devotion (0.067), war (0.057)
PC2: adventure (0.557), friend (0.304), blood (0.207), school (0.192), strigoi (0.159), hogwart (0.149), power (0.145), camp (0.123), band (0.112), magic (0.107)
PC3: family (0.439), land (0.345), throne (0.337), game (0.189), kingdom (0.188), dragon (0.180), balance (0.156), conflict (0.143), enemy (0.139), plot (0.139)
PC4: adventure (0.538), love (0.215), case (0.128), height (0.122), text (0.088), work (0.082), band (0.081), treasure (0.072), chronology (0.068), generation (0.067)
PC5: hogwart (0.489), death (0.222), voldemort (0.216), student (0.177), wizard (0.157), school (0.140), summer (0.137), letter (0.132), witchcraft (0.124), age (0.104)
PC6: adventure (0.347), past (0.338), house (0.315), horror (0.251), apartment (0.193), town (0.188), job (0.165), jess (0.157), night (0.140), question (0.134)


In [33]:
#st knjig po temah

pca_scores = pca.transform(X)
assigned_components = pca_scores.argmax(axis=1)
theme_counts = pd.Series(assigned_components).value_counts().sort_index()

for i, count in theme_counts.items():
    print(f"PC{i+1}: {count} books")

PC1: 47 books
PC2: 31 books
PC3: 37 books
PC4: 59 books
PC5: 36 books
PC6: 40 books


In [16]:
# import matplotlib.pyplot as plt
# labels = X_pca.argmax(axis=1)   

# pairs = [(0,1), (0,2), (0,3), (1,2), (1,3), (2,3)]

# for i, j in pairs:
#     plt.figure()
#     plt.scatter(
#         X_pca[:, i],
#         X_pca[:, j],
#         c=labels,       
#         cmap="tab10"    
#     )
#     plt.xlabel(f"PC{i+1}")
#     plt.ylabel(f"PC{j+1}")
#     plt.title(f"PC{i+1} vs PC{j+1}")
#     plt.colorbar(label="žanr")   
#     plt.show()

# plt.show()

In [17]:
import glob
filepaths_test = glob.glob(r'C:\Users\mokro\Desktop\diploma\najbolj_popularne\naj_ang_opisi\*.txt')[250:]


In [32]:
import os
import re
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

def extract_num(filename):
    match = re.search(r'opis_(\d+)', filename)
    return int(match.group(1)) if match else None


# isti vectorizer, samo tranform uporabimo
X_test = vectorizer.transform(filepaths_test)
X_test_dense = X_test.toarray()
X_test_pca = pca.transform(X_test_dense)


# lahko tudi negativne zato vzamemo aboslutne vrednosti
dominant_pcs = np.argmax(np.abs(X_test_pca), axis=1) + 1 # da zacnemo od pc1 naprej in ne od pc0


#dominant_values = X_test_pca[np.arange(X_test_pca.shape[0]), dominant_pcs - 1]
#dominant_signs = np.where(dominant_values >= 0, "+", "-")


test_filenames = [os.path.basename(f) for f in filepaths_test]


metadata= pd.read_csv(r'C:\Users\mokro\Desktop\diploma\najbolj_popularne\najboljse_knjige_metadata.csv')
metadata['book_id'] = metadata['Knjiga'].apply(lambda x: int(re.search(r'(\d+)', str(x)).group(1)) if re.search(r'(\d+)', str(x)) else None)
id_to_title = dict(zip(metadata['book_id'], metadata['Originalni naslov']))
metadata_new = metadata.drop_duplicates(subset=['book_id'])

results_pca = []
for i, filename in enumerate(test_filenames):
    book_id = extract_num(filename)
    title = id_to_title.get(book_id, "Title Not Found")

    results_pca.append({
        "Filename": filename,
        "ID": book_id,
        "Naslov": title,
        "Komponenta": f"PC{dominant_pcs[i]}",
    })

df_pca_final = pd.DataFrame(results_pca)

df_pca_final

,Filename,ID,Naslov,Komponenta
0,opis_58.txt,58,The Bone Collector,PC1
1,opis_59.txt,59,The Only One Left,PC3
2,opis_6.txt,6,The Stranger,PC2
3,opis_60.txt,60,The Couple Next Door,PC2
4,opis_61.txt,61,Behind Closed Doors,PC6
5,opis_62.txt,62,Final Girls,PC6
6,opis_63.txt,63,No Exit,PC1
7,opis_64.txt,64,The Last Thing He Told Me,PC1
8,opis_65.txt,65,Looking for Alaska,PC1
9,opis_66.txt,66,"The Lion, the Witch and the Wardrobe",PC3
