In [34]:
from sklearn.feature_extraction.text import CountVectorizer
import glob
import pandas as pd
import nltk
import numpy as np
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk import pos_tag

In [35]:
# modeli za ustrezno obdelavo stavkov, besed, ločil....
nltk.download('punkt')     # stavki, besede
nltk.download('wordnet') #lemmatizacija
nltk.download('averaged_perceptron_tagger') #POS tagganje
nltk.download('omw-1.4') 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [36]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [37]:
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\mokro\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

In [38]:
# tokenization and lemmatization 
lemmatizer= WordNetLemmatizer()

In [39]:
# pokupčkamo besede s podobnim korenom, pomenom skupaj
# run, runs, running -> run
def get_wordnet_pos(treebank_tag):
    if treebank_tag.startswith('J'):
        return wordnet.ADJ
    elif treebank_tag.startswith('V'):
        return wordnet.VERB
    elif treebank_tag.startswith('RB'):
        return wordnet.ADV
    elif treebank_tag.startswith('N'):
        return wordnet.NOUN
    else:
        return wordnet.NOUN

In [40]:
def tokenize_lematize(tekst):
    tokens = word_tokenize(tekst.lower())  # vse besede pišemo z malo začetnico
    tagged = pos_tag(tokens)
    return [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged
        if word.isalpha()    # znebimo se ločil, st,...
    ]

In [41]:
import random
from sklearn.feature_extraction import text

In [42]:
# CountVectorizer odstrani 'stopwords' in ustvari nenegativno matriko, na (i, j)-tem mestu
# imamo pojavitev besede i v j-tem dokumentu (glej zapiske na tablici)

#random.seed(42)
# vzamemo 150/200 knjig, ostale bomo potem poskusali uvrstiti med žanre
filepaths = glob.glob(r'C:\Users\mokro\Desktop\diploma\leto_2003\knjige_03_opisi\*.txt')[:150]
#filepaths= random.sample(filepaths, 150)
# min_df=2, max_df=0.9 odstranita redke in pogoste besede, to uniči celoten rezultat
custom_stopwords = list(text.ENGLISH_STOP_WORDS.union({'book', 'novel', 'story', 'author', 'character',
                                                  'edition', 'classic', 'bestseller', 'review',
                                                  'read', 'reader', 'york', 'times', 'new'}))
vectorizer= CountVectorizer(stop_words= 'english', #custom_stopwords, 
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=1, 
                            max_df=0.8)

In [43]:
X = vectorizer.fit_transform(filepaths) 


c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:411: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['far', 'make', 'u'] not in stop_words.
  warnings.warn(


In [44]:
print(X)

# malo lepše, prikaz
dense_matrix = X.toarray()
print(dense_matrix)

#še lepše
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(dense_matrix, columns=feature_names)
print(df.head())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10242 stored elements and shape (150, 4393)>
  Coords	Values
  (0, 2711)	2
  (0, 1348)	1
  (0, 2326)	2
  (0, 4229)	4
  (0, 3266)	2
  (0, 1981)	1
  (0, 3776)	1
  (0, 4342)	1
  (0, 4357)	1
  (0, 100)	1
  (0, 949)	2
  (0, 1193)	2
  (0, 1163)	1
  (0, 3255)	1
  (0, 2729)	1
  (0, 2863)	1
  (0, 4354)	1
  (0, 3727)	1
  (0, 3293)	1
  (0, 2942)	1
  (0, 3169)	1
  (0, 3948)	3
  (0, 48)	1
  (0, 1768)	5
  (0, 4041)	1
  :	:
  (149, 2853)	1
  (149, 1235)	2
  (149, 4352)	1
  (149, 349)	1
  (149, 3210)	1
  (149, 1304)	1
  (149, 1198)	1
  (149, 3577)	1
  (149, 3021)	1
  (149, 530)	1
  (149, 885)	1
  (149, 974)	1
  (149, 1157)	1
  (149, 676)	1
  (149, 1074)	1
  (149, 2100)	1
  (149, 1448)	1
  (149, 2182)	1
  (149, 667)	1
  (149, 307)	1
  (149, 3154)	1
  (149, 1704)	1
  (149, 191)	1
  (149, 2495)	1
  (149, 244)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
   abbreviate  a

In [45]:
def nmf(X, k, max_iter=500, tol=1e-4, random_state=42):
    """
    Nenegativna matrična faktorizacija, ki uporablja pravila za posodobitev elementov na podlagi množenja.

    Parametri:
    -----------
    X : ndarray (m x n)
        Nenegativna matrika
    k : int
        Stevilo komponent (teme/ žanri)
    max_iter : int
        Maksimalno število iteracij
    tol : float
        Toleranca konvergence (izračunano s pomočjo reconstruction error)
    random_state : int
        

    Vrne:
    --------
    W : ndarray (m x k)
    H : ndarray (k x n)
    errors : list
        Reconstruction za vsako iteracijo
    """
    
    np.random.seed(random_state)
    
    m, n = X.shape
    
    #zacnemo z nakljucnimi nenegativnimi vrednostmi
    W = np.random.rand(m, k)
    H = np.random.rand(k, n)
    
    eps = 1e-9
    errors = []
    
    for i in range(max_iter):
        
        # posodabljanje H
        H *= (W.T @ X) / (W.T @ W @ H + eps) # + eps, da ne delimo z 0
        # posodabljanje W
        W *= (X @ H.T) / (W @ (H @ H.T) + eps)
        
        # reconstruction error
        error = np.linalg.norm(X - W @ H, 'fro')
        errors.append(error)
        
        # konvergenca
        if i > 0 and abs(errors[-2] - error) < tol:
            break

    return W, H, errors

In [46]:
# test 

W, H, errors = nmf(X, 4)
print(errors)
#print(W)
#print(H)

[np.float64(128.6727769354265), np.float64(128.02463678858246), np.float64(127.48525351246694), np.float64(126.6668678811145), np.float64(125.37568700596182), np.float64(124.03285191512732), np.float64(123.34640839170818), np.float64(123.07746302139027), np.float64(122.95587757481236), np.float64(122.88633445213206), np.float64(122.83912358275853), np.float64(122.80468890136422), np.float64(122.77800634365921), np.float64(122.75632504156235), np.float64(122.73811681169505), np.float64(122.72255099580073), np.float64(122.70908775703157), np.float64(122.697481693816), np.float64(122.68729612350926), np.float64(122.67824508564301), np.float64(122.67040836945833), np.float64(122.6632492646453), np.float64(122.65548900251), np.float64(122.64810039498087), np.float64(122.64244611614194), np.float64(122.63789960534343), np.float64(122.63407510663815), np.float64(122.63077446177225), np.float64(122.6278605369676), np.float64(122.62520362410574), np.float64(122.62277541552406), np.float64(122.6

In [47]:
feature_names = vectorizer.get_feature_names_out()
for topic_idx, topic in enumerate(H):
    top_words = [feature_names[i] for i in topic.argsort()[-15:]]
    print(f"Tema {topic_idx +1}: {' '.join(top_words)}")

Tema 1: krakauer year great story book american faith make passion u christ franklin live god life
Tema 2: body new force discover murder priory curator paris clue secret work vinci neveu da langdon
Tema 3: heart year thing want new men mother time family man life make woman know love
Tema 4: color boston author story john beane read enron character reader dante time new book world
