In [2]:
#!python -m spacy download en_core_web_sm

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import glob
import pandas as pd
import nltk
from nltk import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk import pos_tag
import wordcloud

In [4]:
# # modeli za ustrezno obdelavo stavkov, besed, ločil....
# nltk.download('punkt')     # stavki, besede
# nltk.download('wordnet') #lemmatizacija
# nltk.download('averaged_perceptron_tagger') #POS tagganje
# nltk.download('omw-1.4') 
# nltk.download('punkt_tab')
# nltk.download('averaged_perceptron_tagger_eng')

In [5]:
# # tokenization and lemmatization 
# lemmatizer= WordNetLemmatizer()

In [6]:
# # pokupčkamo besede s podobnim korenom, pomenom skupaj
# # run, runs, running -> run
# def get_wordnet_pos(treebank_tag):
#     if treebank_tag.startswith('J'):
#         return wordnet.ADJ
#     elif treebank_tag.startswith('V'):
#         return wordnet.VERB
#     elif treebank_tag.startswith('RB'):
#         return wordnet.ADV
#     elif treebank_tag.startswith('N'):
#         return wordnet.NOUN
#     else:
#         return wordnet.NOUN

In [7]:
# def tokenize_lematize(tekst):
#     tokens = word_tokenize(tekst.lower())  # vse besede pišemo z malo začetnico
#     tagged = pos_tag(tokens)
#     return [
#         lemmatizer.lemmatize(word, get_wordnet_pos(tag))
#         for word, tag in tagged
#         if word.isalpha()    # znebimo se ločil, st,...
#     ]

In [8]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [9]:
def tokenize_lematize(tekst):
    doc = nlp(tekst)
    
    izbrane_besede = []
    
    # želimo odstraniti osebe, kraji, jeziki, narodi...
    odstrani_pos = ['PROPN', 'PRON', 'VERB', 'ADV']
    odstrani_entitete = {'PERSON', 'GPE', 'LOC', 'NORP', 'FAC', 'ORG'}
    
    #mnozica prepoznanih entitet
    for token in doc:
        # odstranimo i
        if token.pos_ in odstrani_pos:
            continue
        if token.ent_type_ in odstrani_entitete:
            continue
            
        # spacy ima oznake NOUN, ADJ
        if token.pos_ in ['NOUN', 'ADJ']:
            beseda = token.lemma_.lower()
            # samo crke in dolzina nad 2 znaka
            if beseda.isalpha() and len(beseda) > 2:
                izbrane_besede.append(beseda)
                
    return izbrane_besede

In [10]:
base_vectorizer = CountVectorizer(stop_words='english')
base_stopwords = base_vectorizer.get_stop_words()


custom_words = {
    # založniški šum 
    'book', 'novel', 'story', 'author', 'literature', 'edition', 'seller', 
    'read', 'reader', 'page', 'chapter', 'write', 'writer', 'publish', 
    'publication', 'review', 'times', 'york', 'print', 'copy', 'best', 
    'original', 'classic', 'introduction', 'note', 'debut', 'thriller',
    'unique', 'fascinating', 'scandal', 'major', 'character', 'cover', 'magazine',
    'self', 'series', 'volume', 'masterpiece', 'translation', 'film', 'tale', 'course',
    'trilogy',
    
    # splošni opisi 
    'way', 'thing', 'important', 'practical', 'young', 'boy', 'girl', 
    'human', 'people', 'great', 'good', 'bad', 'true', 'new', 'old',
    'life', 'world', 'everything', 'day', 'time', 'year', 'make',
    'take', 'come', 'think', 'feel', 'know', 'look', 'want', 'large', 'small',
    'man', 'woman', 'literary', 'secret', 'isbn', 'mother', 'sister', 'father',
    'little', 'room', 'place', 'end', 'first', 'second', 'red', 'purple', 'black',
    
    #iz izpisa
    'professional', 'guide', 'experience', 'natural', 'vivid', 'narrative',
    'compelling', 'extraordinary', 'powerful', 'voice', 'mind', 'bestseller', 'essey', 'essay',
    'art', 'tessa', 'lissa', 'daughter', 'son', 'wife', 'brother', 'sister', 'bibliography', 'penguin', 'child'
}


all_stopwords = list(base_stopwords.union(custom_words))

In [11]:
# CountVectorizer odstrani 'stopwords' in ustvari nenegativno matriko, na (i, j)-tem mestu
# imamo pojavitev besede i v j-tem dokumentu (glej zapiske na tablici)

#random.seed(42)
# vzamemo 150/200 knjig, ostale bomo potem poskusali uvrstiti med žanre
filepaths = glob.glob(r'C:\Users\mokro\Desktop\diploma\leto_2003\03_ang_opisi\*.txt')[:150]
#filepaths= random.sample(filepaths, 150)
# min_df=2, max_df=0.9 odstranita redke in pogoste besede, to uniči celoten rezultat
# custom_stopwords = list(text.ENGLISH_STOP_WORDS.union({'book', 'novel', 'story', 'author', 'character',
#                                                   'edition', 'classic', 'bestseller', 'review',
#                                                   'read', 'reader', 'york', 'times', 'new'}))
vectorizer= CountVectorizer(stop_words= all_stopwords, #custom_stopwords, 
                            tokenizer= tokenize_lematize,
                            input = 'filename', 
                            encoding='latin-1', 
                            min_df=3)

In [12]:
X = vectorizer.fit_transform(filepaths) 


c:\Users\mokro\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\feature_extraction\text.py:526: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [13]:
print(X)

# malo lepše, prikaz
dense_matrix = X.toarray()
print(dense_matrix)

#še lepše
feature_names = vectorizer.get_feature_names_out()
df = pd.DataFrame(dense_matrix, columns=feature_names)
print(df.head())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2752 stored elements and shape (150, 555)>
  Coords	Values
  (0, 166)	1
  (0, 15)	1
  (0, 130)	2
  (0, 337)	1
  (0, 357)	1
  (0, 418)	1
  (0, 372)	1
  (0, 512)	1
  (0, 361)	1
  (0, 382)	1
  (0, 207)	1
  (0, 336)	1
  (0, 471)	1
  (0, 108)	1
  (0, 469)	1
  (0, 124)	1
  (0, 199)	1
  (0, 4)	1
  (0, 490)	1
  (0, 123)	1
  (0, 506)	1
  (0, 370)	1
  (0, 290)	1
  (1, 130)	2
  (1, 535)	1
  :	:
  (148, 296)	1
  (148, 239)	1
  (148, 231)	1
  (148, 217)	1
  (148, 9)	1
  (148, 325)	1
  (148, 396)	1
  (148, 261)	1
  (148, 531)	1
  (148, 65)	1
  (148, 491)	1
  (148, 419)	1
  (149, 328)	1
  (149, 262)	1
  (149, 252)	1
  (149, 66)	4
  (149, 77)	1
  (149, 450)	1
  (149, 171)	1
  (149, 27)	1
  (149, 103)	1
  (149, 260)	1
  (149, 364)	1
  (149, 497)	1
  (149, 419)	1
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
   ability  able  accident  account  action  actual  addition  a

In [14]:
from sklearn.decomposition import PCA

In [15]:
pca = PCA(n_components=5)  
X_pca = pca.fit_transform(X)

In [16]:
print(pca.explained_variance_ratio_)
print("Skupaj:", sum(pca.explained_variance_ratio_))

[0.03898474 0.02691507 0.02568675 0.02420714 0.02231722]
Skupaj: 0.13811092105607276


In [17]:
for k in range(1,6):
    pca =PCA(n_components=k)
    X_pca = pca.fit_transform(X)     
    feature_names = vectorizer.get_feature_names_out()
    print(f'stevilo komponent je: ', k)
    for i, comp in enumerate(pca.components_):
        top_words = [feature_names[j] for j in comp.argsort()[-10:]]
        print(f"PC{i+1}: {top_words}")
    print('\n')

stevilo komponent je:  1
PC1: ['marriage', 'wedding', 'country', 'search', 'prison', 'power', 'city', 'heart', 'family', 'love']


stevilo komponent je:  2
PC1: ['marriage', 'wedding', 'country', 'search', 'prison', 'power', 'city', 'heart', 'family', 'love']
PC2: ['emotional', 'home', 'violent', 'account', 'authority', 'school', 'faith', 'religious', 'house', 'family']


stevilo komponent je:  3
PC1: ['marriage', 'wedding', 'country', 'search', 'prison', 'power', 'city', 'heart', 'family', 'love']
PC2: ['emotional', 'home', 'violent', 'account', 'authority', 'school', 'faith', 'religious', 'house', 'family']
PC3: ['savage', 'violence', 'bone', 'habit', 'religious', 'fundamentalist', 'work', 'violent', 'faith', 'creative']


stevilo komponent je:  4
PC1: ['marriage', 'wedding', 'country', 'search', 'prison', 'power', 'city', 'heart', 'family', 'love']
PC2: ['emotional', 'home', 'violent', 'account', 'authority', 'school', 'faith', 'religious', 'house', 'family']
PC3: ['savage', 'violen

In [18]:
pca = PCA(n_components=5)  
X_pca = pca.fit_transform(X)

In [19]:
feature_names = vectorizer.get_feature_names_out()

for i, comp in enumerate(pca.components_):
    top_indices = comp.argsort()[-10:][::-1]
    top_words_with_weights = [f"{feature_names[j]} ({comp[j]:.3f})" for j in top_indices]
    
    print(f"PC{i+1}: {', '.join(top_words_with_weights)}")

PC1: love (0.756), family (0.237), heart (0.185), city (0.173), power (0.124), prison (0.114), search (0.107), country (0.094), wedding (0.094), marriage (0.088)
PC2: family (0.431), house (0.200), religious (0.179), faith (0.164), school (0.156), authority (0.136), account (0.130), violent (0.127), home (0.120), emotional (0.106)
PC3: creative (0.396), faith (0.338), violent (0.236), work (0.225), fundamentalist (0.208), religious (0.176), habit (0.160), bone (0.146), violence (0.138), savage (0.127)
PC4: creative (0.462), habit (0.192), family (0.122), order (0.109), career (0.099), school (0.099), paper (0.098), simple (0.087), beginning (0.081), insight (0.080)
PC5: vampire (0.284), creative (0.279), family (0.247), dark (0.241), city (0.186), war (0.165), night (0.158), beautiful (0.148), power (0.137), habit (0.127)


In [20]:
#st knjig po temah

pca_scores = pca.transform(X)
assigned_components = pca_scores.argmax(axis=1)
theme_counts = pd.Series(assigned_components).value_counts().sort_index()

for i, count in theme_counts.items():
    print(f"PC{i+1}: {count} books")

PC1: 23 books
PC2: 23 books
PC3: 17 books
PC4: 50 books
PC5: 37 books


In [21]:
import glob
filepaths_test = glob.glob(r'C:\Users\mokro\Desktop\diploma\leto_2003\03_ang_opisi\*.txt')[150:]


In [22]:
import os
import re
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA

def extract_num(filename):
    match = re.search(r'opis_(\d+)', filename)
    return int(match.group(1)) if match else None


# isti vectorizer, samo tranform uporabimo
X_test = vectorizer.transform(filepaths_test)
X_test_dense = X_test.toarray()
X_test_pca = pca.transform(X_test_dense)


# lahko tudi negativne zato vzamemo aboslutne vrednosti
dominant_pcs = np.argmax(np.abs(X_test_pca), axis=1) + 1 # da zacnemo od pc1 naprej in ne od pc0


#dominant_values = X_test_pca[np.arange(X_test_pca.shape[0]), dominant_pcs - 1]
#dominant_signs = np.where(dominant_values >= 0, "+", "-")


test_filenames = [os.path.basename(f) for f in filepaths_test]


metadata= pd.read_csv(r'C:\Users\mokro\Desktop\diploma\leto_2003\knjige_03_metadata.csv')
metadata['book_id'] = metadata['Knjiga'].apply(lambda x: int(re.search(r'(\d+)', str(x)).group(1)) if re.search(r'(\d+)', str(x)) else None)
id_to_title = dict(zip(metadata['book_id'], metadata['Originalni naslov']))
metadata_new = metadata.drop_duplicates(subset=['book_id'])

results_pca = []
for i, filename in enumerate(test_filenames):
    book_id = extract_num(filename)
    title = id_to_title.get(book_id, "Title Not Found")

    results_pca.append({
        "Filename": filename,
        "ID": book_id,
        "Naslov": title,
        "Komponenta": f"PC{dominant_pcs[i]}",
    })

df_pca_final = pd.DataFrame(results_pca)

df_pca_final

,Filename,ID,Naslov,Komponenta
0,opis_60.txt,60,The Wife,PC3
1,opis_61.txt,61,The Lake House,PC5
2,opis_63.txt,63,Ilium,PC1
3,opis_64.txt,64,Black: The Birth of Evil,PC1
4,opis_65.txt,65,Out Stealing Horses,PC1
5,opis_66.txt,66,Living History,PC1
6,opis_67.txt,67,Portrait in Death,PC1
7,opis_68.txt,68,Inkheart,PC1
8,opis_69.txt,69,Mister Monday,PC1
9,opis_7.txt,7,The Known World,PC3


In [ ]:
import time
# merimo cas 
start = time.time()
X_test_pca = pca.transform(X_test_dense)
end = time.time()

skupaj = end - start
print(f"Čas klasifikacije PCA (40 testnih dokumentov): {skupaj:.4f} s")
print(f"Povprečen čas na dokument: {skupaj / X_test_dense.shape[0] * 1000:.4f} ms")

Čas klasifikacije PCA (40 testnih dokumentov): 0.0003 s
Povprečen čas na dokument: 0.0084 ms


In [23]:
# import matplotlib.pyplot as plt
# labels = X_pca.argmax(axis=1)   

# pairs = [(0,1), (0,2), (0,3), (1,2), (1,3), (2,3)]

# for i, j in pairs:
#     plt.figure()
#     plt.scatter(
#         X_pca[:, i],
#         X_pca[:, j],
#         c=labels,       
#         cmap="tab10"    
#     )
#     plt.xlabel(f"PC{i+1}")
#     plt.ylabel(f"PC{j+1}")
#     plt.title(f"PC{i+1} vs PC{j+1}")
#     plt.colorbar(label="žanr")   
#     plt.show()

# plt.show()